### ISSUE TITLE
Support for debian jessie

### ISSUE THREAD

**Issue by holms** [sous-chefs/java#159]
It's just doesn't work.

```
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/java/recipes/default.rb
================================================================================


Chef::Exceptions::InvalidCookbookVersion
----------------------------------------
'jessie/sid' does not match 'x.y.z' or 'x.y'


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/java/recipes/set_attributes_from_version.rb:40:in `from_file'
  /var/chef/cache/cookbooks/java/recipes/default.rb:25:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/java/recipes/set_attributes_from_version.rb:

 33:    node.default['java']['openjdk_packages'] = ["openjdk#{node['java']['jdk_version']}"]
 34:  when "arch"
 35:    node.default['java']['java_home'] = "/usr/lib/jvm/java-#{node['java']['jdk_version']}-openjdk"
 36:    node.default['java']['openjdk_packages'] = ["openjdk#{node['java']['jdk_version']}"]
 37:  when "debian"
 38:    node.default['java']['java_home'] = "/usr/lib/jvm/java-#{node['java']['jdk_version']}-#{node['java']['install_flavor']}"
 39:    # Newer Debian & Ubuntu adds the architecture to the path
 40>>   if node['platform'] == 'debian' && Chef::VersionConstraint.new(">= 7.0").include?(node['platform_version']) ||
 41:       node['platform'] == 'ubuntu' && Chef::VersionConstraint.new(">= 12.04").include?(node['platform_version'])
 42:      node.default['java']['java_home'] = "#{node['java']['java_home']}-#{node['kernel']['machine'] == 'x86_64' ? 'amd64' : 'i386'}"
 43:    end
 44:    node.default['java']['openjdk_packages'] = ["openjdk-#{node['java']['jdk_version']}-jdk", "openjdk-#{node['java']['jdk_version']}-jre-headless"]
 45:  when "smartos"
 46:    node.default['java']['java_home'] = "/opt/local/java/sun6"
 47:    node.default['java']['openjdk_packages'] = ["sun-jdk#{node['java']['jdk_version']}", "sun-jre#{node['java']['jdk_version']}"]
 48:  when "windows"
 49:    # Do nothing otherwise we will fall through to the else and set java_home to an invalid path, causing the installer to popup a dialog




Running handlers:
[2014-04-08T03:30:18+00:00] ERROR: Running exception handlers
Running handlers complete

[2014-04-08T03:30:18+00:00] ERROR: Exception handlers complete
[2014-04-08T03:30:18+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 18.711022304 seconds
[2014-04-08T03:30:18+00:00] ERROR: 'jessie/sid' does not match 'x.y.z' or 'x.y'
[2014-04-08T03:30:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by nperez-athena** [comment]
Hi, just want to point out that this still isn't fixed as of version 12.12.15

**Comment by erichelgeson** [comment]
@nperez-athena can you provide which vagrant box would be the equivalent to what your testing on? Can add it in and address any issues. Also what version is 12.12.15 of? (I'm not a deb user)

**Comment by elthariel** [comment]
Same issue with `stretch/sid`.

The ohai value `node['platform_version'] == 'stretch/sid'`.
