### ISSUE TITLE
Error failed to extract file

### ISSUE THREAD

**Issue by guibamp** [sous-chefs/java#439]
Hello, 

I'm new with Chef, could someone please tell me if I'm doing anything wrong? 
If this is because it's not a good idea to use Oracle URL, is there an alternative repository in the internet I can use? Or else, how can I use instead this file if I put it inside `~/chef-repo/cookbooks/mycookbook/files/default` ?

O.S.: Centos 7 64 bits
Chef version: 12.21.4
Java cookbook version: 1.50.0

This is how I invoked this cookbook: 

~/chef-repo/cookbooks/mycookbook/recipes/default.rb:
```
...
include_recipe 'java'
...
```

~/chef-repo/cookbooks/mycookbook/attributes/default.rb:
```
...
default['java']['jdk_version'] = '7'
default['java']['install_flavor'] = 'oracle'
default['java']['jdk']['7']['x86_64']['url'] = 'http://download.oracle.com/otn/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz'
default['java']['oracle']['accept_oracle_download_terms'] = true
...
```

Log when I execute `chef-solo -c solo.rb -j web.json`:
```
...
Recipe: java::set_java_home
  * directory[/etc/profile.d] action create[2017-08-27T22:03:26-04:00] INFO: Processing directory[/etc/profile.d] action create (java::set_java_home line 19)
 (up to date)
  * template[/etc/profile.d/jdk.sh] action create[2017-08-27T22:03:26-04:00] INFO: Processing template[/etc/profile.d/jdk.sh] action create (java::set_java_home line 23)
 (up to date)
Recipe: java::oracle
  * yum_package[tar] action install[2017-08-27T22:03:26-04:00] INFO: Processing yum_package[tar] action install (java::oracle line 57)
 (up to date)
  * java_ark[jdk] action install[2017-08-27T22:03:26-04:00] INFO: Processing java_ark[jdk] action install (java::oracle line 61)
[2017-08-27T22:03:26-04:00] INFO: Adding jdk to /usr/lib/jvm/jdk1.7.0_79

    * yum_package[curl] action install[2017-08-27T22:03:26-04:00] INFO: Processing yum_package[curl] action install (/root/chef-solo/cookbooks/java/providers/ark.rb line 72)
 (up to date)
    - download oracle tarball straight from the server[2017-08-27T22:03:29-04:00] FATAL: Failed to extract file jdk-7u79-linux-x64.tar.gz!

    ================================================================================
    Error executing action `install` on resource 'java_ark[jdk]'
    ================================================================================
    
    SystemExit
    ----------
    exit
    
    Cookbook Trace:
    ---------------
    /root/chef-solo/cookbooks/java/providers/ark.rb:164:in `block (2 levels) in class_from_file'
    /root/chef-solo/cookbooks/java/providers/ark.rb:142:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks/java/recipes/oracle.rb
    
     61: java_ark 'jdk' do
     62:   url tarball_url
     63:   default node['java']['set_default']
     64:   checksum tarball_checksum
     65:   app_home java_home
     66:   bin_cmds bin_cmds
     67:   alternatives_priority node['java']['alternatives_priority']
     68:   retries node['java']['ark_retries']
     69:   retry_delay node['java']['ark_retry_delay']
     70:   connect_timeout node['java']['ark_timeout']
     71:   use_alt_suffix node['java']['use_alt_suffix']
     72:   reset_alternatives node['java']['reset_alternatives']
     73:   download_timeout node['java']['ark_download_timeout']
     74:   proxy node['java']['ark_proxy']
     75:   action :install
     76:   notifies :write, 'log[jdk-version-changed]', :immediately
     77: end
     78: 
     79: if node['java']['set_default'] && platform_family?('debian')
     80:   include_recipe 'java::default_java_symlink'
     81: end
     82: 
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks/java/recipes/oracle.rb:61:in `from_file'
    
    java_ark("jdk") do
      action [:install]
      supports {:report=>true, :exception=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :java_ark
      cookbook_name "java"
      recipe_name "oracle"
      url "http://download.oracle.com/otn/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz"
      default true
      checksum "6f1f81030a34f7a9c987f8b68a24d139"
      app_home "/usr/lib/jvm/java"
      bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jhat", "jinfo", "jmap", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
      alternatives_priority 1062
      connect_timeout 600
      use_alt_suffix true
      reset_alternatives true
      download_timeout 600
      owner "root"
    end
    
    System Info:
    ------------
    chef_version=12.21.4
    platform=centos
    platform_version=7.3.1611
    ruby=ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
    program_name=chef-solo worker: ppid=7975;start=22:02:49;
    executable=/opt/chef/embedded/bin/chef-solo
    
[2017-08-27T22:03:29-04:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-08-27T22:03:29-04:00] ERROR: Running exception handlers
Running handlers complete
[2017-08-27T22:03:29-04:00] ERROR: Exception handlers complete
Chef Client failed. 4 resources updated in 39 seconds
[2017-08-27T22:03:29-04:00] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[2017-08-27T22:03:29-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-27T22:03:29-04:00] ERROR: java_ark[jdk] (java::oracle line 61) had an error: SystemExit: exit
[2017-08-27T22:03:29-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by erichelgeson** [comment]
The best practice is to host it the file yourself on your own artifact repository (eg, S3, artifactory, etc) - I believe that you can not download jdk7 without logging in now so any automation directly pulling from oracle will fail. Please host it yourself and try again. 

Note you wont find any public copies of oracle jdk downloads as that is against their agreements.

**Comment by guibamp** [comment]
Thanks @erichelgeson 
Is it possible to use the file in my local machine where chef is running? How could I do that?

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
