### ISSUE TITLE
jdk_version attribute type enforcement

### ISSUE THREAD

**Issue by dereklwood** [sous-chefs/java#463]
### Cookbook version
2.0.1

### Chef-client version
13.8.5

### Platform Details
CentOS 6.9

### Scenario:
Previously we (perhaps incorrectly) specified `node['java']['jdk_version'] = 7` (Fixnum, not String).  It used to work fine, but with the release of 2.0.1, this now causes an exception (below).  This was introduced possibly unintentionally by [this commit](https://github.com/sous-chefs/java/commit/a31860dfc4f045933c433b7d542d2a3c37057df1).

Perhaps the input can be validated, or converted to a string as it used to, or at least be better documented.

### Steps to Reproduce:
In a wrapper cookbook, set `node['java']['jdk_version'] = 7`

### Expected Result:
cookbook compiles

### Actual Result:
```
================================================================================
Recipe Compile Error in /var/folders/t1/7b6w6b5j6zb5sqrymly5qyf40000gn/T/d20180503-26304-g3j11p/cookbooks/cdap/recipes/base.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /var/folders/t1/7b6w6b5j6zb5sqrymly5qyf40000gn/T/d20180503-26304-g3j11p/cookbooks/java/recipes/openjdk.rb:61:in `block in from_file'
  /var/folders/t1/7b6w6b5j6zb5sqrymly5qyf40000gn/T/d20180503-26304-g3j11p/cookbooks/java/recipes/openjdk.rb:57:in `from_file'
  /var/folders/t1/7b6w6b5j6zb5sqrymly5qyf40000gn/T/d20180503-26304-g3j11p/cookbooks/java/recipes/default.rb:22:in `from_file'
  /var/folders/t1/7b6w6b5j6zb5sqrymly5qyf40000gn/T/d20180503-26304-g3j11p/cookbooks/cdap/recipes/prerequisites.rb:24:in `from_file'
  /var/folders/t1/7b6w6b5j6zb5sqrymly5qyf40000gn/T/d20180503-26304-g3j11p/cookbooks/cdap/recipes/base.rb:22:in `from_file'

Relevant File Content:
----------------------
/var/folders/t1/7b6w6b5j6zb5sqrymly5qyf40000gn/T/d20180503-26304-g3j11p/cookbooks/java/recipes/openjdk.rb:

 54:    notifies :write, 'log[jdk-version-changed]', :immediately
 55:  end
 56:  
 57:  java_alternatives 'set-java-alternatives' do
 58:    java_location jdk.java_home
 59:    default node['java']['set_default']
 60:    priority jdk.alternatives_priority
 61>>   bin_cmds node['java']['jdk'][node['java']['jdk_version']]['bin_cmds']
 62:    action :set
 63:    only_if { platform_family?('debian', 'rhel', 'fedora', 'amazon') }
 64:  end
 65:  
 66:  if node['java']['set_default'] && platform_family?('debian')
 67:    include_recipe 'java::default_java_symlink'
 68:  end
 69:  
 70:  # We must include this recipe AFTER updating the alternatives or else JAVA_HOME

System Info:
------------
chef_version=13.8.5
platform=centos
platform_version=6.9
ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin14]
program_name=/Users/derek/.chefdk/gem/ruby/2.4.0/bin/rspec
executable=/Users/derek/.chefdk/gem/ruby/2.4.0/bin/rspec
```

**Comment by jeffbyrnes** [comment]
👍 this was tripping me up in a big way in the `zookeeper` cookbook

**Comment by majormoses** [comment]
Looks like it was reported also in #481 and I have proposed #486 which should resolve this.
