### ISSUE TITLE
Certificate resource missing assignment to variable

### ISSUE THREAD

**Issue by empirechaotix** [sous-chefs/java#477]
### Cookbook version
2.1.0

### Chef-client version
14.2.0

### Platform Details
CentOS

### Scenario:
Adding certificate to cacerts using ssl_endpoint

### Steps to Reproduce:

    java_certificate "empirechaotixnet" do
      java_home "/usr/local/java/x86/jdk_8u171_alt"
      keystore_path "/usr/local/java/x86/jdk_8u171_alt/jre/lib/security/cacerts"
      cert_alias 'empirechaotixnet'
      ssl_endpoint 'empirechaotix.net:443'
      action :install
    end

### Expected Result:
It should retrieve the cert from the specified end point, and inject it into the cacerts of the specified java.

### Actual Result:
During runtime using the resource call above the following exception will occur:

java_certificate[empirechaotixnet] action install

           ================================================================================
           Error executing action `install` on resource 'java_certificate[empirechaotixnet]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `certout' for #<#<Class:0x000000000634ec60>:0x0000000004cbf468>

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/java/resources/certificate.rb:121:in `fetch_certdata'
           /tmp/kitchen/cache/cookbooks/java/resources/certificate.rb:37:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/jenkins_node/recipes/jenkins_java.rb

            55:     java_certificate "empirechaotixnet" do
            56:       java_home "/usr/local/java/#{java_arch}/jdk_#{java_version}_alt"
            57:       keystore_path "/usr/local/java/#{java_arch}/jdk_#{java_version}_alt/jre/lib/security/cacerts"
            58:       cert_alias 'empirechaotixnet'
            59:       ssl_endpoint 'empirechaotix.net:443'
            60:       action :install
            61:     end
            62:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/jenkins_node/recipes/jenkins_java.rb:55:in `block (2 levels) in from_file'

           java_certificate("empirechaotixnet") do
             action [:install]
             default_guard_interpreter :default
             declared_type :java_certificate
             cookbook_name "jenkins_node"
             recipe_name "jenkins_java"
             java_home "/usr/local/java/x86/jdk_seven_alt"
             keystore_path "/usr/local/java/x86/jdk_seven_alt/jre/lib/security/cacerts"
             cert_alias "empirechaotixnet"
             ssl_endpoint "empirechaotix.net:443"
           end

           System Info:
           ------------
           chef_version=14.3.37
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client

       Running handlers:
       [2018-07-19T14:35:18+00:00] ERROR: Running exception handlers
       [2018-07-19T14:35:18+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-07-19T14:35:18+00:00] ERROR: Exception handlers complete
       [2018-07-19T14:35:18+00:00] ERROR: Exception handlers complete
       Chef Client failed. 5 resources updated in 05 minutes 26 seconds
       [2018-07-19T14:35:18+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-07-19T14:35:18+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-07-19T14:35:18+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-07-19T14:35:18+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-07-19T14:35:18+00:00] FATAL: NoMethodError: java_certificate[empirechaotixnet] (jenkins_node::jenkins_java line 55) had an error: NoMethodError: undefined method `certout' for #<#<Class:0x000000000634ec60>:0x0000000004cbf468>
       [2018-07-19T14:35:18+00:00] FATAL: NoMethodError: java_certificate[empirechaotixnet] (jenkins_node::jenkins_java line 55) had an error: NoMethodError: undefined method `certout' for #<#<Class:0x000000000634ec60>:0x0000000004cbf468>

### Proposed Solution:
Replace line 121 in certificate.rb with:
certout = cmd.stdout.split(/-----BEGIN CERTIFICATE-----|-----END CERTIFICATE-----/)

**Comment by empirechaotix** [comment]
Seems to have been resolved as part of - https://github.com/sous-chefs/java/pull/473

Thanks 👍
