### ISSUE TITLE
bin_cmds missing on ubuntu

### ISSUE THREAD

**Issue by spuder** [sous-chefs/java#481]
### Cookbook version
2.2.0

### Chef-client version
Chef 13

### Platform Details
Ubuntu 16.04

### Scenario:

Using test kitchen with cookbook 2.2.0 on ubuntu you will get this error

```
================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/java/recipes/default.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `[]' for nil:NilClass

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/java/recipes/openjdk.rb:61:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/java/recipes/openjdk.rb:57:in `from_file'
         /tmp/kitchen/cache/cookbooks/java/recipes/default.rb:22:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/java/recipes/openjdk.rb:

        54:    notifies :write, 'log[jdk-version-changed]', :immediately
        55:  end
        56:
        57:  java_alternatives 'set-java-alternatives' do
        58:    java_location jdk.java_home
        59:    default node['java']['set_default']
        60:    priority jdk.alternatives_priority
        61>>   bin_cmds node['java']['jdk'][node['java']['jdk_version']]['bin_cmds']
        62:    action :set
        63:    only_if { platform_family?('debian', 'rhel', 'fedora', 'amazon') }
        64:  end
        65:
        66:  if node['java']['set_default'] && platform_family?('debian')
        67:    include_recipe 'java::default_java_symlink'
        68:  end
        69:
        70:  # We must include this recipe AFTER updating the alternatives or else JAVA_HOME

       Platform:
       ---------
       x86_64-linux


       Running handlers:
       [2018-08-06T19:48:32+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-08-06T19:48:32+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2018-08-06T19:48:32+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-08-06T19:48:32+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-08-06T19:48:32+00:00] ERROR: undefined method `[]' for nil:NilClass
       [2018-08-06T19:48:32+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

In test kitchen file I have jdk_version set

```
    attributes:
      java:
        jdk_version: 8
```

The documentation stats that setting `bin_cmds` should not be required if using a non oracle java

> bin_cmds: array of binary commands that should be symlinked to /usr/bin, examples are mvn, java, javac, etc. These cmds must be in the bin subdirectory of the extracted folder. Will be ignored if this java_oracle_install is not the default

**Comment by hrak** [comment]
Hi @spuder, i ran into the same issue, and it was because i had defined `default['java']['jdk_version'] = 8` (so as an integer). Changing it to `default['java']['jdk_version'] = '8'` fixed it.
